### ISSUE TITLE
1.3.5, 1.4.0, 1.10.2 dispatcher not send response to broker

### ISSUE THREAD

**Issue by chris93111** [knative-extensions/eventing-natss#381]
**Describe the bug**
after upgrade 1.3.0 to 1.3.5, knative sequence with broker not work correctly, the dispatch controller don't accept content-type  "application/cloudevents+json", it's generate error dispatcher/consumer.go:73 failed to handle message failed to forward reply to http://broker-ingress.knative-eventing.svc.cluster.local/xxxxxx, specversion: no specversion 

So the response message is not send to broker

If content-type is application/json the dispatcher don't have error, but msg is not send to broker

i used the app appender https://github.com/knative/eventing/blob/main/cmd/appender/main.go same as documentation

 **Expected behavior**
response msg send to broker

 **To Reproduce**
knative service with response cloudevent

 **Knative release version**
1.2.2

**Comment by astelmashenko** [comment]
I will try to reproduce and fix this issue in context of https://github.com/knative-sandbox/eventing-natss/pull/382

Please correct me if I'm worng,  this tutorial https://knative.dev/docs/eventing/flows/sequence/sequence-with-broker-trigger/#create-the-trigger-targeting-the-sequence should reproduce the issue.

**Comment by chris93111** [comment]
Hi @astelmashenko yes

**Comment by astelmashenko** [comment]
This is what I received locally
```json
{
    "caller": "dispatcher/consumer.go:73",
    "error": "failed to forward reply to http://sequence-kn-sequence-1-kn-jsm-channel.default.svc.cluster.local: Post \"http://sequence-kn-sequence-1-kn-jsm-channel.default.svc.cluster.local\": dial tcp 10.102.254.116:80: i/o timeout",
    "is_leader": true,
    "knative.dev/controller": "knative.dev.eventing-natss.pkg.channel.jetstream.dispatcher.Reconciler",
    "knative.dev/key": "default/sequence-kn-sequence-0",
    "knative.dev/kind": "messaging.knative.dev.NatsJetStreamChannel",
    "knative.dev/pod": "jetstream-ch-dispatcher-7db57f9b49-xjt5h",
    "knative.dev/traceid": "964b22d8-37d5-4655-a0a0-91577f819343",
    "level": "error",
    "logger": "jetstream-channel-dispatcher",
    "msg": "failed to handle message",
    "stacktrace": "knative.dev/eventing-natss/pkg/channel/jetstream/dispatcher.(*Consumer).MsgHandler\n\tknative.dev/eventing-natss/pkg/channel/jetstream/dispatcher/consumer.go:73\ngithub.com/nats-io/nats%2ego.(*js).subscribe.func1\n\tgithub.com/nats-io/nats.go@v1.15.0/js.go:1512\ngithub.com/nats-io/nats%2ego.(*Conn).waitForMsgs\n\tgithub.com/nats-io/nats.go@v1.15.0/nats.go:2715",
    "sub_uid": "bf2808b0-51ae-4f2b-81fa-583e615cf17d",
    "ts": "2022-12-12T10:46:30.394Z"
}
```
Key thing here is 
```
failed to forward reply to http://sequence-kn-sequence-1-kn-jsm-channel.default.svc.cluster.local: Post \"http://sequence-kn-sequence-1-kn-jsm-channel.default.svc.cluster.local\": dial tcp 10.102.254.116:80: i/o timeout
```

I also checked that both binary (application/json) and structured (application/cloudevents+json) events are working if I send directly to channel.

I checked [documentation](https://knative.dev/docs/eventing/flows/sequence/) and there is a notice:

> Sequence needs "hairpin" traffic. Please verify that your pod can reach itself via the service IP. If the "hairpin" traffic is not available, you can reach out to your cluster administrator since its a cluster level (typically CNI) setting.

Not sure if it is exactly the case of the issue.

**Comment by chris93111** [comment]
@astelmashenko it's work with version 1.3.0, it's not a problem with CNI

**Comment by astelmashenko** [comment]
@chris93111 , I added retry config and it is working now, so it seems there was an issue with timeouts, please try this:
```yaml
apiVersion: flows.knative.dev/v1
kind: Sequence
metadata:
  name: sequence
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: NatsJetStreamChannel
    spec:
      consumerConfigTemplate:
        deliverPolicy: New
        ackWait: 60s
  steps:
    - delivery:
        backoffDelay: PT5S
        backoffPolicy: exponential
        retry: 5
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: first
    - delivery:
        backoffDelay: PT5S
        backoffPolicy: exponential
        retry: 5
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: second
    - delivery:
        backoffDelay: PT5S
        backoffPolicy: exponential
        retry: 5
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: third
  reply:
    ref:
      kind: Broker
      apiVersion: eventing.knative.dev/v1
      name: default
```

**Comment by chris93111** [comment]
@astelmashenko Hi no is not work for me the sequence-display don't receive event and in nats the channel as only one event, so the last reply with change type is not send to broker

This is my manifests

```
apiVersion: flows.knative.dev/v1
kind: Sequence
metadata:
  name: test
  namespace: cfg-events
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: NatsJetStreamChannel
    spec:
      consumerConfigTemplate:
        ackWait: 30s
        deliverPolicy: New
      stream:
        config:
          duplicateWindow: 0s
          maxAge: 168h
  reply:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: test
      namespace: cfg-events
  steps:
    - delivery:
        backoffDelay: PT5S
        backoffPolicy: exponential
        retry: 5
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: first
        namespace: cfg-events
    - delivery:
        backoffDelay: PT5S
        backoffPolicy: exponential
        retry: 5
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: second
        namespace: cfg-events
    - delivery:
        backoffDelay: PT5S
        backoffPolicy: exponential
        retry: 5
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: third
        namespace: cfg-events
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: first
  namespace: cfg-events
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containerConcurrency: 0
      containers:
        - env:
            - name: MESSAGE
              value: ' - Handled by 0'
          image: gcr.io/knative-releases/knative.dev/eventing/cmd/appender
          name: user-container
          readinessProbe:
            successThreshold: 1
            tcpSocket:
              port: 0
          resources: {}
      enableServiceLinks: false
      timeoutSeconds: 300
  traffic:
    - latestRevision: true
      percent: 100
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: second
  namespace: cfg-events
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containerConcurrency: 0
      containers:
        - env:
            - name: MESSAGE
              value: ' - Handled by 1'
          image: gcr.io/knative-releases/knative.dev/eventing/cmd/appender
          name: user-container
          readinessProbe:
            successThreshold: 1
            tcpSocket:
              port: 0
          resources: {}
      enableServiceLinks: false
      timeoutSeconds: 300
  traffic:
    - latestRevision: true
      percent: 100
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: third
  namespace: cfg-events
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containerConcurrency: 0
      containers:
        - env:
            - name: MESSAGE
              value: ' - Handled by 2'
            - name: TYPE
              value: samples.http.mod3
          image: gcr.io/knative-releases/knative.dev/eventing/cmd/appender
          name: user-container
          readinessProbe:
            successThreshold: 1
            tcpSocket:
              port: 0
          resources: {}
      enableServiceLinks: false
      timeoutSeconds: 300
  traffic:
    - latestRevision: true
      percent: 100
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sequence-display
  namespace: cfg-events
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: '1'
      creationTimestamp: null
    spec:
      containerConcurrency: 0
      containers:
        - image: gcr.io/knative-releases/knative.dev/eventing/cmd/event_display
          name: user-container
          readinessProbe:
            successThreshold: 1
            tcpSocket:
              port: 0
          resources: {}
      enableServiceLinks: false
      timeoutSeconds: 300
  traffic:
    - latestRevision: true
      percent: 100
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: sequence-trigger
  namespace: cfg-events
spec:
  broker: test
  filter:
    attributes:
      source: test/a
      type: test/b
  subscriber:
    ref:
      apiVersion: flows.knative.dev/v1
      kind: Sequence
      name: test
      namespace: cfg-events
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: display-trigger
  namespace: cfg-events
spec:
  broker: test
  filter:
    attributes:
      type: samples.http.mod3
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: sequence-display
      namespace: cfg-events
```

In Nats 

```
│ KN_CFG_EVENTS__TEST_KN_SEQUENCE_0                          │             │ 2022-12-16 19:40:29 │ 1        │ 476 B │ 8.38s        │
│ KN_CFG_EVENTS__TEST_KN_SEQUENCE_1                          │             │ 2022-12-16 19:40:29 │ 1        │ 497 B │ 6.40s        │
│ KN_CFG_EVENTS__TEST_KNE_TRIGGER                            │             │ 2022-12-03 18:52:06 │ 1        │ 499 B │ 8.40s        │
│ KN_CFG_EVENTS__TEST_KN_SEQUENCE_2                          │             │ 2022-12-16 19:40:29 │ 1        │ 512 B │ 4.40s   
```

All channel have one message , normaly the KN_CFG_EVENTS__TEST_KNE_TRIGGER take 2 message, the first and the last in response of last consumer in sequence with change type

```
~ # nats stream view KN_CFG_EVENTS__TEST_KNE_TRIGGER
[7] Subject: cfg-events.test-kne-trigger._knative Received: 2022-12-16T21:15:33Z

  Nats-Msg-Id: 59b9e9f5-38f0-4df8-a816-0738c935a14f

{"specversion":"1.0","id":"59b9e9f5-38f0-4df8-a816-0738c935a14f","source":"test/a","type":"test/b","datacontenttype":"application/json","time":"2022-12-16T21:15:33.582005568Z","data":{"data":"test"},"knativearrivaltime":"2022-12-16T21:15:33.600884463Z","knativebrokerttl":"255","traceparent":"00-c76ec2a79c286c7a036d95c4e058ab46-0bb2568669a95eb9-00","tracestate":""}

21:20:22 Reached apparent end of data
~ # nats stream view KN_CFG_EVENTS__TEST_KN_SEQUENCE_0 
[7] Subject: cfg-events.test-kn-sequence-0._knative Received: 2022-12-16T21:15:33Z

  Nats-Msg-Id: 59b9e9f5-38f0-4df8-a816-0738c935a14f

{"specversion":"1.0","id":"59b9e9f5-38f0-4df8-a816-0738c935a14f","source":"test/a","type":"test/b","datacontenttype":"application/json","time":"2022-12-16T21:15:33.582005568Z","data":{"data":"test"},"traceparent":"00-c76ec2a79c286c7a036d95c4e058ab46-e857b51d4138a837-00","tracestate":"","knativearrivaltime":"2022-12-16T21:15:33.600884463Z"}

21:20:33 Reached apparent end of data
~ # nats stream view KN_CFG_EVENTS__TEST_KN_SEQUENCE_1
[7] Subject: cfg-events.test-kn-sequence-1._knative Received: 2022-12-16T21:15:35Z

  Nats-Msg-Id: 59b9e9f5-38f0-4df8-a816-0738c935a14f

{"specversion":"1.0","id":"59b9e9f5-38f0-4df8-a816-0738c935a14f","source":"test/a","type":"test/b","datacontenttype":"application/json","time":"2022-12-16T21:15:33.582005568Z","data":{"id":0,"message":" - Handled by 0"},"knativearrivaltime":"2022-12-16T21:15:33.600884463Z","traceparent":"00-c76ec2a79c286c7a036d95c4e058ab46-4e2e57b2df8df171-00","tracestate":""}

21:20:35 Reached apparent end of data
~ # nats stream view KN_CFG_EVENTS__TEST_KN_SEQUENCE_2
[7] Subject: cfg-events.test-kn-sequence-2._knative Received: 2022-12-16T21:15:37Z

  Nats-Msg-Id: 59b9e9f5-38f0-4df8-a816-0738c935a14f

{"specversion":"1.0","id":"59b9e9f5-38f0-4df8-a816-0738c935a14f","source":"test/a","type":"test/b","datacontenttype":"application/json","time":"2022-12-16T21:15:33.582005568Z","data":{"id":0,"message":" - Handled by 0 - Handled by 1"},"knativearrivaltime":"2022-12-16T21:15:33.600884463Z","tracestate":"","traceparent":"00-c76ec2a79c286c7a036d95c4e058ab46-b404f9467ee33aac-00"}

21:20:36 Reached apparent end of data
```
