### ISSUE TITLE
Trigger reset NatsJetStreamChannel config

### ISSUE THREAD

**Issue by chris93111** [knative-extensions/eventing-natss#432]
**Describe the bug**
With Broker and custom config channeltemplate, the trigger reset the configuration of the NatsJetStreamChannel

stream is empty and consumerConfigTemplate disappear

 **Expected behavior**
custom config persistent 

 **To Reproduce**
create a broker with custom config

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: config-natjsm-channel-cfg
  namespace: cfg-events
data:
  channelTemplateSpec: |-
    apiVersion: messaging.knative.dev/v1alpha1
    kind: NatsJetStreamChannel
    spec:
      consumerConfigTemplate:
        deliverPolicy: Last
      stream:
        config:
          maxAge: 30m0s
```

```
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: test
  namespace: cfg-events
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: config-natjsm-channel-cfg
    namespace: knative-eventing
  delivery:
    backoffDelay: PT30S
    backoffPolicy: exponential
    retry: 2
```

Create Trigger

```
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: display-trigger
  namespace: cfg-events
  labels:
    eventing.knative.dev/broker: test
spec:
  broker: test
  filter:
    attributes:
      type: samples.http.mod3
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: sequence-display
      namespace: cfg-events
```
The spec generated for natsjetreamchannel after broker create 
```
spec:
  consumerConfigTemplate:
    ackWait: 0s
    deliverPolicy: Last
    replayPolicy: ''
  delivery:
    backoffDelay: PT30S
    backoffPolicy: exponential
    retry: 2
  stream:
    config:
      duplicateWindow: 0s
      maxAge: 30m0s
```

After trigger creation 

```
  delivery:
    backoffDelay: PT30S
    backoffPolicy: exponential
    retry: 2
  stream: {}
  subscribers:
    - delivery:
        backoffDelay: PT30S
        backoffPolicy: exponential
        retry: 2
      generation: 1
      replyUri: 'http://broker-ingress.knative-eventing.svc.cluster.local/cfg-events/test'
      subscriberUri: >-
        http://broker-filter.knative-eventing.svc.cluster.local/triggers/cfg-events/display-trigger/3c4023d4-56bb-434b-a17d-d0856e1bcee5
      uid: 3adf1d09-02f5-4daa-a3b5-cb297afb16ca
```

 **Knative release version**
1.9.0

 **Additional context**
1.10.3 dispatcher jsm version

Patched by knative eventing controller https://github.com/knative/eventing/blob/d89300ce34fa0d757d4193837f7b0de88a04f2e2/pkg/reconciler/subscription/subscription.go#L439C22-L439C39

**Comment by astelmashenko** [comment]
When I tried to create a broker and then trigger then I see that it is added as a subscriber which is expected:
```
spec:
  consumerConfigTemplate:
    ackWait: 3m45s
    deliverPolicy: New
    maxAckPending: 22
    maxDeliver: 2
    replayPolicy: ''
  delivery:
    retry: 0
    timeout: PT22S
  stream:
    config:
      duplicateWindow: 0s
      maxAge: 0s
      maxBytes: 1000000000
      replicas: 1
      retention: Limits
  subscribers:
    - delivery:
        backoffDelay: PT0.2S
        backoffPolicy: exponential
        retry: 2
        timeout: PT32S
      generation: 1
      replyUri: http://broker-ingress.knative-eventing.svc.cluster.local/default/default
      subscriberUri: >-
        http://broker-filter.knative-eventing.svc.cluster.local/triggers/default/display-trigger/9dca64a8-d43e-4ee1-97a1-86d711dad84f
      uid: d5983bb7-3121-4f99-872f-51001589d7f8
```
