### ISSUE TITLE
Incorrect number of retries when when MaxDeliver bigger then 1

### ISSUE THREAD

**Issue by astelmashenko** [knative-extensions/eventing-natss#457]
**Describe the bug**
Retries are configured on Channel.consumerConfigTemplate.maxDeliver and trigger/subscriber level. Dispatcher sends messages via DispatchMessageWithRetries based on trigger/subscriber config.

If I set both retries: on trigger/subscriber level and Channel.consumerConfigTemplate.maxDeliver and a targer service will timeout each request, then I get (maxDeliver*retryMax) number of retries.

 **Expected behavior**
In case of bad request or timeout maxDeliver should be used, message should be terminated.

 **To Reproduce**
Setup a broker and trigger (or channel and subscription)
```yaml
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: "default"
``` 
broker config:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-br-default-channel
  namespace: knative-eventing
data:
  channel-template-spec: |-
    apiVersion: messaging.knative.dev/v1alpha1
    kind: NatsJetStreamChannel
    spec:
      stream:
        config:
          retention: Limits
          maxBytes: 1000000000
          replicas: 1
      consumerConfigTemplate:
        deliverPolicy: New
        maxAckPending: 100
        maxDeliver: 3
        ackWait: 300s
      delivery:
        backoffDelay: PT0.2S
        backoffPolicy: exponential
        retry: 0
        timeout: PT300S
```
trigger
```yaml
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: display-trigger
spec:
  broker: default
  filter:
    attributes:
      type: fun.display
  delivery:
    backoffDelay: PT2S
    backoffPolicy: exponential
    retry: 3
    timeout: PT5S
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
```
and create a function with delay more then 5s and send event to broker

 **Knative release version**
1.10.x 

cc @dan-j
