### ISSUE TITLE
JetStream release combined YAML assets contain namespaces on cluster level resources

### ISSUE THREAD

**Issue by epalchan** [knative-extensions/eventing-natss#549]
**Describe the bug**
The `eventing-jsm.yaml` asset in all releases contains namespaces on `ClusterRoleBinding` resources, as well as having `RoleBinding` resources reference `ClusterRole` resource with a namespace.
2 examples:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jetstream-ch-dispatcher
  namespace: knative-eventing
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jetstream-ch-dispatcher
subjects:
  - kind: ServiceAccount
    name: jetstream-ch-dispatcher
    namespace: knative-eventing

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jetstream-ch-dispatcher-configmap-reader
  namespace: knative-eventing
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eventing-config-reader
subjects:
  - kind: ServiceAccount
    name: jetstream-ch-dispatcher
    namespace: knative-eventing
```

 **Expected behavior**
Applying the manifest would work and allow to version lock deployments of the NATS extension if required to a specific release.

 **To Reproduce**
N/A

 **Knative release version**
1.10.7 (appears to be in all versions though)

 **Additional context**
N/A
