### ISSUE TITLE
jetstream-ch-dispatcher: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by metacoma** [knative-extensions/eventing-natss#638]
**Describe the bug**
After sending a CloudEvent to the broker based on NatsJetStreamChannel, the JetStream channel dispatcher pods go into a CrashLoopBack state.

 **Expected behavior**
The jetstream-ch-dispatcher is working fine.

 **To Reproduce**
```
$ kubectl -n user-alice get NatsJetStreamChannel
NAME                              READY   REASON   URL                                                                                    AGE
alice-laptop-broker-kne-trigger   True             http://alice-laptop-broker-kne-trigger-kn-jsm-channel.user-alice.svc.cluster.local   28h
$ kubectl -n user-alice get broker alice-laptop-broker
NAME                  URL                                                                                         AGE   READY   REASON
alice-laptop-broker   http://broker-ingress.knative-eventing.svc.cluster.local/user-alice/alice-laptop-broker   28h   True    
$ TRACE_ID="$(tr -dc 'a-f0-9' < /dev/urandom | head -c 32)"
$ SPAN_ID="$(tr -dc 'a-f0-9' < /dev/urandom | head -c 16)"
$ TRACEPARENT="00-${TRACE_ID}-${SPAN_ID}-01"
$ export INGRESS_NS=istio-system                                                                                                                
$ export INGRESS_HOST=$(kubectl -n "$INGRESS_NS" get service "$INGRESS_NAME" -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
$ URI=/user-alice/user-laptop-broker
$ SOURCE="org.mindwm.v1.mindmap-terminal"
$ SUBJECT="org.mindwm.${USER}.$(hostname -s).tmux.xxxx.09fb195c-c419-6d62-15e0-51b6ee990922.0.2"
$ TYPE=org.mindwm.v1.ping

$ echo '{}' | curl \
    -vvvv \
    -XPOST  \
    "http://${INGRESS_HOST}${URI}"  \
    -H "Host: broker-ingress.knative-eventing.svc.cluster.local" \
    -H "Content-Type: application/json" \
    -H "traceparent: $TRACEPARENT" \
    -H "Ce-specversion: 1.0" \
    -H "Ce-id: $TRACE_ID" \
    -H "ce-subject: ${SUBJECT}" \
    -H "ce-source: ${SOURCE}" \
    -H "ce-type: ${TYPE}" \
    -d@-

*   Trying 10.24.142.129:80...
* Connected to 10.24.142.129 (10.24.142.129) port 80 (#0)
> POST /user-alice/user-laptop-broker HTTP/1.1
> Host: broker-ingress.knative-eventing.svc.cluster.local
> User-Agent: curl/7.81.0
> Accept: */*
> Content-Type: application/json
> traceparent: 00-fb5ad83d50f68e7d7daa83cd98c975b3-aad4300870a00aca-01
> Ce-specversion: 1.0
> Ce-id: fb5ad83d50f68e7d7daa83cd98c975b3
> ce-subject: org.mindwm.alice.laptop.tmux.xxxx.0.2
> ce-source: org.mindwm.v1.mindmap-terminal
> ce-type: org.mindwm.v1.ping
> Content-Length: 28

**** CURL HANGS HERE FOR A COUPLE OF MINUTES

> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 202 Accepted
< allow: POST, OPTIONS
< date: Wed, 26 Feb 2025 21:11:55 GMT
< content-length: 0
< x-envoy-upstream-service-time: 233667
< server: istio-envoy
< 
```

 **Knative release version**
eventing-natss v1.17.0
knative-serving 1.17.0
knative-eventing 1.17.0

 **Additional context**
jetstream-ch-dispatcher logs
```
{"level":"info","ts":"2025-02-26T20:44:41.282Z","logger":"jetstream-channel-dispatcher","caller":"channel/event_receiver.go:239","msg":"Could not extr
act channel","commit":"50718b7-dirty","knative.dev/pod":"jetstream-ch-dispatcher-56d56d8d64-bfn76","error":"cannot map host to channel: laptop-host-broker-kne-trigger-kn-jsm-channel.user-alice.svc.cluster.local"}                                                                                     
{"level":"info","ts":"2025-02-26T20:44:41.282Z","logger":"jetstream-channel-dispatcher","caller":"channel/event_receiver.go:239","msg":"Could not extr
act channel","commit":"50718b7-dirty","knative.dev/pod":"jetstream-ch-dispatcher-56d56d8d64-bfn76","error":"cannot map host to channel: laptop-host-b
roker-kne-trigger-kn-jsm-channel.user-alice.svc.cluster.local"} 
...
{"level":"error","ts":"2025-02-26T20:45:11.116Z","logger":"jetstream-channel-dispatcher","caller":"dispatcher/message_dispatcher.go:259","msg":"failed
 to execute message{error 26 0  Post \"http://broker-filter.knative-eventing.svc.cluster.local/triggers/user-alice/laptop-trigger-to-user-broker-tr
igger/61f15820-efa7-409c-87a7-e7d70eaecff7\": net/http: request canceled (Client.Timeout exceeded while awaiting headers)} {dispatch_resp_code 11 500 
 <nil>}","commit":"50718b7-dirty","knative.dev/pod":"jetstream-ch-dispatcher-56d56d8d64-bfn76","knative.dev/controller":"knative.dev.eventing-natss.pk
g.channel.jetstream.dispatcher.Reconciler","knative.dev/kind":"messaging.knative.dev.NatsJetStreamChannel","knative.dev/traceid":"89e7f783-f9bb-49d8-8
7a5-62e53e0fa731","knative.dev/key":"user-alice/laptop-host-broker-kne-trigger","is_leader":false,"is_leader":false,"sub_uid":"9fcf694a-8bac-492d-8
dbd-79d098730ffa","msg_id":"96ff4911c3313df3486d6bf42bc65124","stacktrace":"knative.dev/eventing-natss/pkg/channel/jetstream/dispatcher.processDispatc
hResult\n\tknative.dev/eventing-natss/pkg/channel/jetstream/dispatcher/message_dispatcher.go:259\nknative.dev/eventing-natss/pkg/channel/jetstream/dis
patcher.send\n\tknative.dev/eventing-natss/pkg/channel/jetstream/dispatcher/message_dispatcher.go:177\nknative.dev/eventing-natss/pkg/channel/jetstrea
m/dispatcher.SendMessage\n\tknative.dev/eventing-natss/pkg/channel/jetstream/dispatcher/message_dispatcher.go:125\nknative.dev/eventing-natss/pkg/chan
nel/jetstream/dispatcher.(*PushConsumer).doHandle\n\tknative.dev/eventing-natss/pkg/channel/jetstream/dispatcher/push_consumer.go:132\nknative.dev/eve
nting-natss/pkg/channel/jetstream/dispatcher.(*PushConsumer).MsgHandler.func1\n\tknative.dev/eventing-natss/pkg/channel/jetstream/dispatcher/push_cons
umer.go:90"}                                                               
panic: runtime error: invalid memory address or nil pointer dereference                                                                               
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1d92ff6]

goroutine 435 [running]:
knative.dev/eventing-natss/pkg/channel/jetstream/utils.parseBackoffFuncAndDelay(0x20b9500?)
        knative.dev/eventing-natss/pkg/channel/jetstream/utils/consumerconfig.go:130 +0x16
knative.dev/eventing-natss/pkg/channel/jetstream/utils.CalculateNakDelayForRetryNumber(0x1, 0xc001380180?)
        knative.dev/eventing-natss/pkg/channel/jetstream/utils/consumerconfig.go:114 +0x1b
knative.dev/eventing-natss/pkg/channel/jetstream/dispatcher.processDispatchResult({0x2735218, 0xc000e0b020}, 0xc0003f2380, 0xc000a378c0, 0x1, 0xc000eb
0bc0, {0x270dac0, 0xc000dc4a20})
        knative.dev/eventing-natss/pkg/channel/jetstream/dispatcher/message_dispatcher.go:278 +0x69d
knative.dev/eventing-natss/pkg/channel/jetstream/dispatcher.send(0xc0005fc0c0, {0x2735218, 0xc000e94db0}, {0x27350e8, 0xc000eb48f0}, {0x0, 0xc000718cf
0, 0x0, 0x0}, 0x6fc23ac00, ...)
        knative.dev/eventing-natss/pkg/channel/jetstream/dispatcher/message_dispatcher.go:177 +0x7da
knative.dev/eventing-natss/pkg/channel/jetstream/dispatcher.SendMessage(0xc0005fc0c0, {0x2735218, 0xc000e94db0}, {0x27350e8, 0xc000eb48f0}, {0x0?, 0xc
000718cf0?, 0x0?, 0x0?}, 0x6fc23ac00, ...)
        knative.dev/eventing-natss/pkg/channel/jetstream/dispatcher/message_dispatcher.go:125 +0x1b0
knative.dev/eventing-natss/pkg/channel/jetstream/dispatcher.(*PushConsumer).doHandle(0xc000b880f0, {0x2735218, 0xc000e94b40}, 0xc0003f2380)
        knative.dev/eventing-natss/pkg/channel/jetstream/dispatcher/push_consumer.go:132 +0x75c
knative.dev/eventing-natss/pkg/channel/jetstream/dispatcher.(*PushConsumer).MsgHandler.func1()
        knative.dev/eventing-natss/pkg/channel/jetstream/dispatcher/push_consumer.go:90 +0x14d
created by knative.dev/eventing-natss/pkg/channel/jetstream/dispatcher.(*PushConsumer).MsgHandler in goroutine 434
        knative.dev/eventing-natss/pkg/channel/jetstream/dispatcher/push_consumer.go:86 +0x67

```

**Comment by mwmahlberg** [comment]
Have the same problem, with events being sent by Camel-K. Same integration with an imc works fine.

**Comment by astelmashenko** [comment]
Thanks for reporting, I'll try to find time and look at it.

**Comment by mwmahlberg** [comment]
> I was not able to reporduce. I used versions the same as you, except knative-eventing 1.17.3

Interesting enough, I am using the [operator v1.17.0](https://operatorhub.io/operator/knative-operator/stable/knative-operator.v1.17.0), which unsurprisingly rolls out 1.17.0 by default. Setting `spec.version` to v1.17.3 causes an error during deployment:

```yaml
# SNIP kubectl get -n knative-eventing knativeeventings.operator.knative.dev knative-eventing -o yaml | yq -M '.status.conditions | map(select(.reason=="Error"))'
- lastTransitionTime: "2025-03-07T14:43:19Z"
  message: 'Install failed with message: the manifests of the target version 1.17.3 are not available to this release'
  reason: Error
  status: "False"
  type: InstallSucceeded
- lastTransitionTime: "2025-03-07T14:43:19Z"
  message: 'Install failed with message: the manifests of the target version 1.17.3 are not available to this release'
  reason: Error
  status: "False"
  type: Ready
# /SNIP
```

For 


```yaml
# SNIP kubectl get -n knative-eventing knativeeventings.operator.knative.dev knative-eventing -o yaml | kubectl neat
apiVersion: operator.knative.dev/v1beta1
kind: KnativeEventing
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: knative-eventing
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: knative-eventing
  namespace: knative-eventing
spec:
  config:
    br-default-channel:
      channel-template-spec: |-
        apiVersion: messaging.knative.dev/v1alpha1
        kind: NatsJetStreamChannel
        spec:
          stream:
            config:
              retention: Limits
              maxBytes: 1000000000
              replicas: 1
          consumerConfigTemplate:
            deliverPolicy: New
            maxDeliver: 1
    br-defaults:
      default-br-config: |
        # This is the cluster-wide default broker channel.
        clusterDefault:
          brokerClass: MTChannelBasedBroker
          apiVersion: v1
          kind: ConfigMap
          name: natsjs-channel
          namespace: knative-eventing
        namespaceDefaults:
          default:
            apiVersion: messaging.knative.dev/v1
            kind: InMemoryChannel
    default-ch-webhook:
      default-ch-config: |
        # This is the cluster-wide default broker channel.
        clusterDefault:
          apiVersion: messaging.knative.dev/v1alpha1
          kind: NatsJetStreamChannel
          spec:
            stream:
              config:
                retention: Limits
                maxBytes: 1000000000
                replicas: 1
            consumerConfigTemplate:
              deliverPolicy: New
              maxDeliver: 1
        namespaceDefaults:
          default:
            apiVersion: messaging.knative.dev/v1
            kind: InMemoryChannel
  version: 1.17.3
```

I am not sure, but from my gut-feeling I'd say that the operator is probably the most used "installation" method for knative. At least it is a prominent one. I was under the assumption that a new release of eventing would be available within the operator. So as far as I can see, I probably have to wait until v1.18 of the operator. Thanks a million for your help!
